### ISSUE TITLE
Can't push to this because of my other github account

### ISSUE THREAD

**Issue by frannyml** [eecs183/git_exercise#1]
Hi, 

I think my other github account SSH is preventing me from pushing to git exercise.  In order to clone my group's repo which I've been invited to through a my umich github account I created, I had to invite my personal github account to be a contributer.  Do you think you might be able to do the same here or add my other github username to the 183 org so the SSH will allow me to push / pull? FrannyMendesLevitin

thanks! or email me at fmendes@umich.edu

**Comment by asebring13** [comment]
Hi,

Not sure what group you sent this to but I think you have the wrong email!

Alyssa

**Comment by dshann** [comment]
Hello,
I think you may have the wrong email.
Best,
Declan

On Wed, Mar 30, 2016 at 8:22 AM, frannyml <notifications@github.com> wrote:

> Hi,
>
> I think my other github account SSH is preventing me from pushing to git
> exercise. In order to clone my group's repo which I've been invited to
> through a my umich github account I created, I had to invite my personal
> github account to be a contributer. Do you think you might be able to do
> the same here or add my other github username to the 183 org so the SSH
> will allow me to push / pull? FrannyMendesLevitin
>
> thanks! or email me at fmendes@umich.edu
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eecs183/git_exercise/issues/1>
>



-- 
Declan Shannon
University of Michigan Undergraduate
Cell: (231)-709-7186

**Comment by wisotsky** [comment]
I am not in 183 please delete this thread

**Comment by julesWu** [comment]
I am not in 183 please delete this thread

**Comment by maspnairs** [comment]
I was in 183 last semester. Not this semester.

**Comment by sabihb** [comment]
As was I. It has been closed - everyone please stop replying.

**Comment by jonathanchun** [comment]
Stop replying to this email thread immediately, it is going to everyone on
the list.

On Wed, Mar 30, 2016 at 12:58 PM, maspnairs <notifications@github.com>
wrote:

> I was in 183 last semester. Not this semester.
> On Mar 30, 2016 12:54 PM, "julesWu" <notifications@github.com> wrote:
>
> > I am not in 183 please delete this thread
> >
> > Sent from my iPhone
> >
> > > On Mar 30, 2016, at 12:18 PM, wisotsky <notifications@github.com>
> wrote:
> > >
> > > I am not in 183 please delete this thread
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/eecs183/git_exercise/issues/1#issuecomment-203524880
> >
>
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eecs183/git_exercise/issues/1#issuecomment-203526268>
>



-- 
Thanks,
Jonathan Chun

**Comment by arbitrarygithub** [comment]
Okay apparently all of you don't understand how email works. Replying with
"I am not in 183 please delete this thread" will send that reply to
everyone associate with this mailing list. Just like all the people did
before and how my message will be sent to everyone as well.

So for all of us to stop receiving messages, everyone needs to stop
replying and just ignore it.

/end thread

**Comment by houseofburgess** [comment]
but I am not in 183 please delete this thread

**Comment by penlandm** [comment]
Tbt to EECS 183 amirite so glad that's over lol

**Comment by rnbrewer** [comment]
everyone please stop replying to this thread whether or not you are in eecs
183.

**Comment by msavich** [comment]
Contact Bill Arthur about it, he is a professor for EECS 183 and he also
sent an email earlier in this thread.

Please stop replying now.

On Wednesday, March 30, 2016, houseofburgess <notifications@github.com>
wrote:

> but I am not in 183 please delete this thread
>
> On Wed, Mar 30, 2016 at 1:02 PM, arbitrarygithub <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Okay apparently all of you don't understand how email works. Replying
> with
> > "I am not in 183 please delete this thread" will send that reply to
> > everyone associate with this mailing list. Just like all the people did
> > before and how my message will be sent to everyone as well.
> >
> > So for all of us to stop receiving messages, everyone needs to stop
> > replying and just ignore it.
> >
> > /end thread
> > On Mar 30, 2016 12:55 PM, "julesWu" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > >
> > > I am not in 183 please delete this thread
> > >
> > > Sent from my iPhone
> > >
> > >
> > > > On Mar 30, 2016, at 12:18 PM, wisotsky <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > > >
> > > > I am not in 183 please delete this thread
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/eecs183/git_exercise/issues/1#issuecomment-203527278
> >
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eecs183/git_exercise/issues/1#issuecomment-203528270>
>


-- 
*Mel Savich*
University of Michigan | Class of 2018
College of Literature, Science, and the Arts <http://www.lsa.umich.edu/>
Computer Science B.S. | French and Francophone Studies B.A. | Women's
Studies B.A.
msavich@umich.edu | (248) 943-2251

**Comment by musaabm** [comment]
You should also contact Matt Hicks, another professor for EECS 183. He might be able to help with your issue.

Best,
Musaab
